name: Manual Java CI Build

on:
  push:
    branches: [ "feature-splitscreen" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 25
      uses: actions/setup-java@v4
      with:
        java-version: '25' # Burayı 25 yaparak gereksinimi karşılıyoruz
        distribution: 'oracle' # Java 25 şu an en sağlıklı Oracle veya temurin ile bulunur
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build --no-daemon # Daemon bazen hata verebilir, kapatmak daha temizdir

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Controlify-Splitscreen-Jar
        path: build/libs/*.jar
