name: Manual Java CI Build

on:
  push:
    branches: [ "feature-splitscreen" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 25
      uses: actions/setup-java@v4
      with:
        java-version: '25'
        distribution: 'oracle' # Java 25 için şu an en güvenli dağıtım
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      # --no-daemon kullanarak bellek hatalarını ve sürüm çakışmalarını önlüyoruz
      run: ./gradlew build --no-daemon 

    - name: Upload Artifact
      if: success() # Sadece başarılı olursa dosyayı yükle
      uses: actions/upload-artifact@v4
      with:
        name: Controlify-Splitscreen-Jar
        path: build/libs/*.jar
